# Site settings
title: Joshua J Harris
header-img: img/home-bg.jpg
email: joshua.jharris13@gmail.com
description: "Where my thoughts live"
baseurl: ""
url: "http://joshuajharris.com"
img: "https://raw.githubusercontent.com/joshuajharris/joshuajharris.github.io/master/img/meta-image.jpg"
twitter_username: Joshua_J_Harris
github_username:  joshuajharris
linkedin_username: joshuajh

# Build settings
markdown: kramdown
highlighter: rogue
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
